<a href="https://colab.research.google.com/github/lufegaro21/Luisa_GarciaRondon_KC/blob/main/Taller1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.	Tienen el siguiente arreglo : 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Como es posible obtener el siguiente resultado:
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


In [30]:
import numpy as np
arr = np.array ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = [1,3,5,7,9]
arr.put(indices,-1)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


2.	Tienen el siguiente input:
np.arange(10)
Como se puede hacer para obtener el siguiente resultado:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])



In [105]:
a = np.arange(10).reshape(2,-1)
np.array(a)





array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

3.	Con base en el siguiente input:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Obtener el siguiente resultado
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])


In [81]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
np.concatenate((a, b), axis=0)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

4.	Con base en el siguiente input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Obtener el siguiente output
array([2, 4])


In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=a[a==b]
c=list(set(c))
print(c)

[2, 4]


5.	Del siguiente input:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
Obtener el siguiente output
array([1,2,3,4])


In [32]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a[0:4]

array([1, 2, 3, 4])

6.	Con el siguiente input:
a = np.array([2, 6, 1, 9, 10, 3, 27])
Obtener:
(array([6, 9, 10]),)


In [27]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[[1,3,4,]],


(array([ 6,  9, 10]),)

7.	Invertir las filas de un arreglo de matriz 2D
arr = np.arange(9).reshape(3,3)
Output deseado:
array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])


In [29]:
arr = np.arange(9).reshape(3,3)
arr [: : -1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])